### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Robo)
add_subdirectory(RoboContent)
add_subdirectory(App)
add_subdirectory(Generated)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Roboplugin
    RoboContentplugin
    Generated_QtQuick3D_Sceneplugin)